language: python
python:
  - "3.7"
before_install:
  - mv secrets.dist.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass --version
  - "hass -c . --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"'
