button_card_templates: !include button_card_templates.yaml

title: ''
views:
  - path: home
    theme: integrated-dark-theme
    type: custom:grid-layout
    layout:
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .         .           .             ."
        "sidebar  entrance  main_floor  office        ."
        "sidebar  home      media       master_suite  ."
        "sidebar  footer    footer      footer        ."
      mediaquery:
        '(max-width: 800px)':
          grid-gap: calc(var(--custom-layout-card-padding) * 1.5)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .         .             ."
            ".  sidebar   sidebar       ."
            ".  entrance  main_floor    ."
            ".  home      media         ."
            ".  office    master_suite  ."
            ".  footer    footer        ."
            ".  .         .             ."
        '(max-width: 1200px)':
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .         .             ."
            "sidebar  entrance  main_floor    ."
            "sidebar  home      media         ."
            "sidebar  office    master_suite  ."
            "sidebar  footer    footer        ."
            "sidebar  .         .             ."
    badges: []
    cards:

      #################################################
      #                                               #
      #                   SIDEBAR                     #
      #                                               #
      #################################################

      - type: markdown
        view_layout:
          grid-area: sidebar
        content: >
          {% set attributes = states.sensor.template_sidebar.attributes |
          default %}

          {% for template in attributes %}

          {{ state_attr('sensor.template_sidebar', template) }}

          {% endfor %}
        style:
          .: >
            ha-card{background-color:#00000010;border-radius:0;min-height:100vh;animation:ha-card
            1s forwards}@keyframes ha-card{0%,100%{border-right:.1vw solid
            rgba(58,69,73,.2)}}@media screen and
            (max-width:800px){ha-card{background:0
            0;min-height:100%;animation:none}}
          ha-markdown:
            .: >
              ha-markdown{padding:var(--custom-layout-card-padding) 2vw 0
              var(--custom-layout-card-padding)!important;pointer-events:none}@media
              screen and (max-width:800px){ha-markdown{padding:0!important}}
            $: >
              p>span{font-family:SF
              Text;font-size:var(--markdown-sidebar-clock-font-size);font-weight:200;line-height:var(--markdown-sidebar-clock-line-height);letter-spacing:-.05vw;margin-left:-.3vw;color:var(--ha-card-header-color)}p>span>span{position:relative;top:-.09em}p{font-family:SF
              Display;font-size:var(--markdown-sidebar-font-size);line-height:var(--markdown-sidebar-line-height);font-weight:300;letter-spacing:.06vw;color:#6a7377}p>b{color:var(--ha-card-header-color)}@media
              screen and
              (max-width:1200px){p>span{font-size:calc(var(--markdown-sidebar-clock-font-size)
              * 1.4);line-height:calc(var(--markdown-sidebar-clock-line-height)
              * 1.4)}p{font-size:calc(var(--markdown-sidebar-font-size) *
              1.4);line-height:calc(var(--markdown-sidebar-line-height) *
              1.4)}}@media screen and
              (max-width:800px){p>span{font-size:calc(var(--markdown-sidebar-clock-font-size)
              * 2.6);line-height:calc(var(--markdown-sidebar-clock-line-height)
              * 2.6)}p{font-size:calc(var(--markdown-sidebar-font-size) *
              2.6);line-height:calc(var(--markdown-sidebar-line-height) *
              2.6);letter-spacing:.16vw}}
      - type: grid
        view_layout:
          grid-area: sidebar
        cards:
          - type: button
            icon: mdi:information-outline
          - type: button
            icon: mdi:arrow-up-bold-circle-outline
            hold_action:
              action: call-service
              service: homeassistant.update_entity
              service_data:
                entity_id: sensor.hacs

      #################################################
      #                                               #
      #                  ENTRANCE                     #
      #                                               #
      #################################################

      - type: vertical-stack
        title: Entrance
        view_layout:
          grid-area: entrance
        cards:
          - type: picture-glance
            entities:
              - camera.front_door_g4_doorbell
            camera_image: camera.front_door_g4_doorbell

          - type: grid
            columns: 3
            cards:
              - type: custom:button-card
                entity: lock.front_door
                name: Front Door
                template:
                  - base
                  - loader

              - type: custom:button-card
                entity: switch.front_porch
                name: Porch
                template:
                  - light
                  - icon_spot
                  - loader

      #################################################
      #                                               #
      #                 MAIN FLOOR                    #
      #                                               #
      #################################################

      - type: grid
        title: Main Floor
        columns: 3
        view_layout:
          grid-area: main_floor
        cards:
          - type: custom:button-card
            entity: light.main_floor # hue_group
            name: Main floor
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.living_room_primary
            name: Living room
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.living_room_corner
            name: Andrew's office
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.kitchen
            name: Kitchen
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.butlers_pantry
            name: Bar
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: climate.living_room
            name: Living Room
            style:
              top: 48%
              left: 15%
              width: 20%
            custom_fields:
              thermostat: >
                [[[ const state = entity.attributes.current_temperature; 
                return ` <text x="50%" y="54%" fill="#8d8e90" font-size="24%" text-anchor="middle" alignment-baseline="middle">${state}°</text></svg>`; ]]]
            styles:
              custom_fields:
                thermostat:
                  [filter: "[[[ return entity.state === 'off' ? 'invert(1)' : 'none'; ]]]", 
                  top: 15%, left: 40%, font-size: 3vw, position: absolute, opacity: 0.6]
            template:
              - base

      #################################################
      #                                               #
      #               JESSES OFFICE                   #
      #                                               #
      #################################################

      - type: grid
        title: Jesse's Office
        columns: 3
        view_layout:
          grid-area: office
        cards:
          - type: custom:button-card
            entity: light.spare_room # hue_group
            name: Jesse's Office
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.spare_room_fixture
            name: Overhead
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.office_backlight_plug
            name: Accent
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: light.elgato_key_light
            name: Left Key
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: light.elgato_key_light_right
            name: Right Key
            template:
              - light
              - icon_spot

      #################################################
      #                                               #
      #                    HOME                       #
      #                                               #
      #################################################

      - type: grid
        title: Home
        columns: 3
        view_layout:
          grid-area: home
        cards:
          - type: entity-button
            tap_action:
              action: toggle
            entity: script.good_morning
            icon: hass:weather-sunset-up

          - type: entity-button
            tap_action:
              action: toggle
            entity: script.1523806783160
            icon: hass:weather-sunset-down

          - type: entity-button
            tap_action:
              action: toggle
            entity: script.1514647809398
            icon: hass:power-sleep




      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################
      # TODO

      - type: markdown
        view_layout:
          grid-area: footer
        content: >
          {{ state_attr('sensor.template_coronavirus', 'template') }}
        style: #force style - duplicate of themes markdown
          {.: "ha-card,ha-markdown{background:0 0;padding:0!important;pointer-events:none;margin-top:-1vw}ha-markdown{overflow:hidden}\n", ha-markdown$: "ha-markdown-element{opacity:.6;font-size:1.26vw;font-weight:400;--mdc-icon-size:1.2vw;font-family:SF Display;letter-spacing:.05vw;line-height:0;white-space:nowrap}ha-icon{vertical-align:3%;opacity:.4}@media screen and (max-width:800px){ha-markdown-element{display:none}}\n"}

