sensor:
  - unique_id: sidebar
    state: template
    attributes:
      time: |
        {%- set hours = '<span>' + now().strftime('%H') + '<span>' %}
        {%- set minutes = '</span>' + now().strftime('%M') + '</span>' %}
        {{ hours }}:{{ minutes }}
      date: |
        <font color='#6a7377'><b>
          {{- now().strftime("%A, %B %-d") }}
        </b></font>
      greet: |
        <b>
        {%- set time = now().hour %}
        {%- if time <= 1 -%} Good night 游땜
        {%- elif time <= 3 -%} Good night 游땱
        {%- elif time <= 5 -%} Good night 游땺
        {%- elif time <= 7 -%} Good morning 游눨
        {%- elif time <= 9 -%} Good morning 驕됊잺
        {%- elif time <= 10 -%} Good morning 游뗵
        {%- elif time <= 13 -%} Good day 游땕
        {%- elif time <= 15 -%} Good day 游땙
        {%- elif time <= 17 -%} Good day 游녦
        {%- elif time <= 19 -%} Good evening 游녦
        {%- elif time <= 22 -%} Good evening 游땗
        {%- elif time <= 23 -%} Good evening 游봆
        {%- else %} Good evening 游봆
        {%- endif -%}
        </b>
      active: |
        <b>
        {%- set lights = [
        ] %}

        {%- set switches = [
        ] %}

        {%- set lights_on = lights | selectattr('state','eq','on') | list %}
        {%- set lights_name = lights | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

        {%- set switches_on = switches | selectattr('state','eq','on') | list %} 
        {%- set switches_name = switches | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

        {%- if (lights_on | length == 0) and (switches_on | length > 0) -%} 
          {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} 칛r p친

        {%- elif (lights_on | length == 1) and (switches_on | length == 1) -%}
          {{ lights_name }} och {{switches_name }} 칛r p친

        {%- elif (lights_on | length == 1) and (switches_on | length > 1) -%}
          {{ lights_name }}, {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} 칛r p친

        {%- elif (lights_on | length > 1) and (switches_on | length == 1) -%}
          {{ lights_on | length }} lampor och {{ switches_name }} 칛r p친

        {%- elif (lights_on | length > 1) and (switches_on | length > 1) -%}
          {{ lights_on | length }} lampor, {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} 칛r p친

        {%- elif (lights_on | length == 1) and (switches_on | length == 0) -%}
          {{ lights_name }} 칛r p친

        {%- elif (lights_on | length > 1) and (switches_on | length == 0) -%}
          {{ lights_on | length }} lampor 칛r p친

        {%- else %}
          <font color='#6a7377'>Everything is off</font>
        {%- endif -%}
        </b>
      weather: |
        {%- if not is_state('sensor.temperature', 'unknown') %}
          {%- set temperature = states('sensor.temperature') | float %}
          {%- set unit = state_attr('sensor.temperature', 'unit_of_measurement') %}
          {%- if not is_state('sensor.chance_of_precip', 'unknown') %}
            {%- set precip = states('sensor.chance_of_precip') | round %}
          {%- else %}
            {%- set precip = 0 %}
          {%- endif %}
          
          {%- if temperature > 0 and precip > 30 %}
            {%- set precip_kind = "rain 驕덢잺" %}
          {%- elif temperature > 0 %}
            {%- set precip_kind = "rain" %}
          {%- else %}
            {%- set precip_kind = "snow 仇勇" %}
          {%- endif %}
        
          {{ states('sensor.condition') }} at {{ temperature }}{{ unit }}
          {%- if precip > 0 -%}
            {{ '\u0020' }}with a {{ precip }}% chance for {{ precip_kind }}
          {%- endif %}
        {%- else %}
          Unable to load weather...
        {%- endif %}

  - unique_id: public_ip
    icon: mdi:ip
    state: 192.168.1.1
